root = "$WORK_DIR"


# Servo

[browsers.servo]
build_dir = "target"
env = [
  "CC=clang",
  "CXX=clang++",
  "RUST_LOG=error,devtools=debug",
  "UV_PROJECT_ENVIRONMENT=.devcontainer-venv",
]
remote = "git@github.com:servo/servo.git"

[browsers.servo.commands]
bootstrap = """
  curl -LsSf https://astral.sh/uv/install.sh | sh
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  ./mach bootstrap
"""
build = "./mach build"
run = "./mach run"
test = "./mach wpt"


# Firefox

[browsers.firefox]
build_dir = "obj"
container_packages = ["git", "make", "python3", "sccache", "libasound2"]
env = ["CC=clang", "CXX=clang++", "SCCACHE_SERVER_PORT=4201"]
remote = "git@github.com:mozilla-firefox/firefox.git"

[browsers.firefox.commands]
bootstrap = "./mach bootstrap"
build = "./mach build"
run = "./mach run"
test = "./mach wpt"


# WebKit

[browsers.webkit]
build_dir = "WebKitBuild"
env = ["CC=clang", "CXX=clang++", "SCCACHE_SERVER_PORT=4202"]
remote = "git@github.com:WebKit/WebKit.git"
use_wkdev = true


# Chromium

[browsers.chromium]
build_dir = "out"
remote = """
  [ ! -d 'depot_tools' ] && git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
  export PATH="$PWD/depot_tools:$PATH"
  mkdir chromium-main
  cd chromium-main
  fetch --nohooks chromium
"""
